addons:
  sonarcloud:
    organization: "se2-mehoba-github"
    token:
      secure: $SONAR_TOKEN

  jobs:
    include:
      - stage: "Unit Tests & SonarCloud Analysis"
        script:
          - gradle jacocoTestReport
          - gradle sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY




language: java
sudo: false
script: mvn clean verify